### ISSUE TITLE
undefined tunny function

### ISSUE THREAD

**Issue by masukomi** [dirk/quickhook#4]
when attempting to build with `go1.12.14` I get 

    pre_commit.go:102:15: undefined: tunny.CreatePoolGeneric

It should be noted that while this function does exist in the version of tunny specified by glide it no longer exists in the current version of tunny. I'm not suggesting that's the bug (it does exist in what glide pulled down). I'm suggesting that _if_ you're going to poke it anyway, you may want to update to the latest tunny API.

**Comment by dirk** [comment]
@masukomi: Thanks for the report! I'll check this out tomorrow and see how easy it is to update to a newer version of `tunny`.
